# Generated by Django 4.2.7 on 2025-11-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
